### ISSUE TITLE
Import and Export

### ISSUE THREAD

**Issue by Tramp99** [Smileynator/blender-mdb-addon#1]
when trying to import a .mdb file from Witcher1, an error occurs:

Python: Traceback (most recent call last):
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-mdb-addon-master\import_mdb.py", line 390, in load
    mdb = parse_mdb(f)
          ^^^^^^^^^^^^
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-mdb-addon-master\import_mdb.py", line 358, in parse_mdb
    assert magic == b'MDB0'
           ^^^^^^^^^^^^^^^^
AssertionError

when trying to export a model from Blender, an error occurs:

Python: Traceback (most recent call last):
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-mdb-addon-master\__init__.py", line 119, in execute
    return export_mdb.save(self, context, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-mdb-addon-master\export_mdb.py", line 699, in save
    indexed_strings = get_unique_names()
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-mdb-addon-master\export_mdb.py", line 56, in get_unique_names
    for bone in bpy.data.armatures[0].bones:
                ~~~~~~~~~~~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

**Comment by Tramp99** [comment]
I will add that when importing the original model with bones, this error occurs

Python: Traceback (most recent call last):
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-mdb-addon-master\__init__.py", line 119, in execute
    return export_mdb.save(self, context, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-mdb-addon-master\export_mdb.py", line 703, in save
    bones = get_bone_data(indexed_strings)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-mdb-addon-master\export_mdb.py", line 116, in get_bone_data
    bone_data['group'] = bone['group']
                         ~~~~^^^^^^^^^
KeyError: 'bpy_struct[key]: key "group" not found'

**Comment by Smileynator** [comment]
I am sorry, are you trying to import a model from a completely different game with this tool?
If so, i highly doubt it would work. Otherwise, i would love to hear what model you are trying to work with, and i can see what i can do to fix it.
